# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'user'

require 'grpc'
require_relative 'user_pb'

module User
  module UserService
    # -----------------User service-----------------
    #
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user.UserService'

      rpc :GetUser, ::User::GetUserRequest, ::User::User
    end

    Stub = Service.rpc_stub_class
  end
end
